### ISSUE TITLE
Rename project for clarity - RSS3 is an existing standard 

### ISSUE THREAD

**Issue by kevinmarks** [NaturalSelectionLabs/RSS3-Protocol#22]
Aaron Swartz defined RSS3 20 years ago. 
Spec: http://www.aaronsw.com/2002/rss30
Announcement: http://www.aaronsw.com/weblog/000574

Maybe you can be RSS4 instead?

**Comment by lossor75** [comment]
I assumed that's the difference between web3.0 and web3, rss3.0 and rss3

**Comment by AboutRSS** [comment]
This is my concern too. Should have been clarified in the first place.

**Comment by kecrily** [comment]
@kevinmarks If I remember correctly, the official considered this point. That's why RSS3 is used instead of RSS3.0, which is like Web3.0

**Comment by tontb** [comment]
The rss3.io site itself reads rss3 'the feed in web3.0', making the OP's point, regardless of the mentioned 'consideration'

**Comment by DIYgod** [comment]
We would love to see an update of the RSS standard, but it has stopped updating for a long time and there is no way to continue the update of the RSS standard, but we also do not want to stop the search for free distribution of information, so we created a new protocol RSS3, RSS stands for a tribute to the history and 3 stands for Web3.

RSS has its version 2.0 3.0, and RSS3 will have its version 2.0 3.0, they are not related in any way.

**Comment by jalcine** [comment]
> We would love to see an update of the RSS standard, but it has stopped updating for a long time and there is no way to continue the update of the RSS standard, but we also do not want to stop the search for free distribution of information, so we created a new protocol RSS3, RSS stands for a tribute to the history and 3 stands for Web3.
> 
> RSS has its version 2.0 3.0, and RSS3 will have its version 2.0 3.0, they are not related in any way.

The lack of an update in RSS gave us Atom and it's extensible by design (being the basis of things like podcasts and ActivityStreams).
